# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e85e31bbd86cdd81ec645c81ec32f326accab0f303b053446bd2a3f59320d6fecc72222c4a7bd7efbfec7b6a7dee96aeb12c700f4e2b84f16ca934752cbf42c

test:
  secret_key_base: f67e6077d2423d6dc15ebd1c4bbdd5a04508041cb03bd84b03af683916cb304b7b17c82f5f387192eba04df32aa6ed92a7d79bbcd07ebb193edb98e41c3fd5e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
